### ISSUE TITLE
Making it work with Kotlin 1.1

### ISSUE THREAD

**Issue by arafalov** [vektory79/kotlin-script-parser-test#1]
This repo still seems to be the only example of trying to get parser to work outside of test framework or actual source. But it does not seem to work with latest Kotlin as classes were moved around and variables removed.

Any chance it could be updated to run with 1.1? I saw a number of people looking for something like this. I have a project idea myself and was not able to get this example (or any other approach) to work.

**Comment by vektory79** [comment]
Thank you to point me that my example is out of date. I'll see what can be done as soon as I find some time.

**Comment by vektory79** [comment]
Yeah! I dit it!

**Comment by arafalov** [comment]
Thank you very much. Большое спасибо!

One of the extension of the example could be to actually iterate through functions and print their content or something. And there is no need for the test file, as it can actually use its own source as the test file. 

Inception!
