### ISSUE TITLE
Update to kotlin 1.3.61

### ISSUE THREAD

**Issue by chippmann** [vektory79/kotlin-script-parser-test#2]
I know this test repo is quite old, but i just came across this and find it incredibly useful!
I tried updating it to kotlin 1.3.61 but I continuously get runtime errors about some classes not found. And i think my knowledge of the compiler is just not good enough to make it work with the new kotlin versions.
Any change of upgrading this to kotlin 1.3.61?

**Comment by chippmann** [comment]
I was just able to get it to work. If you are interested i could make a pull request

**Comment by vektory79** [comment]
Cool to hear it!
If you can to make the PR, I will be glad.
